#pragma once

// ─────────────────────────────────────────────────────────────────────────────
//  index_html.h — Single-page Dashboard (Medication Monitor + Sound Config)
//  Redesigned: big numbers, one page, no tabs, sound track editor
// ─────────────────────────────────────────────────────────────────────────────

static const char index_html[] =
"<!doctype html><html lang=th><head>"
"<meta charset=utf-8>"
"<meta name=viewport content='width=device-width,initial-scale=1'>"
"<link rel=preconnect href='https://fonts.googleapis.com'>"
"<link rel=preconnect href='https://fonts.gstatic.com' crossorigin>"
"<link href='https://fonts.googleapis.com/css2?family=Manrope:wght@700;800;900&family=Inter:wght@400;500;600;700&display=swap' rel=stylesheet>"
"<title>SOVEREIGN — Auto Pill Dispenser</title>"
"<style>"
/* ─ Reset & Variables (Stitch Design) ─ */
":root{--bg:#0a141f;--s-low:#121c28;--s-mid:#17202c;--s-hi:#212b37;--s-top:#2c3542;--s-deep:#050f1a;"
"--panel:#212b37;--line:rgba(60,74,68,.8);"
"--txt:#d9e3f3;--muted:#bacac2;"
"--ok:#50f0c3;--ok2:#22d3a8;--bad:#ffb4ab;--warn:#ffcf8f;--blue:#b9c8dc;"
"--r:16px;--shadow:0 20px 40px rgba(0,0,0,.4)}"

"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:'Inter',system-ui,sans-serif;background:var(--bg);color:var(--txt);min-height:100vh;"
"background-image:radial-gradient(ellipse 70% 35% at 50% -5%,rgba(80,240,195,.14),transparent 60%);}"
/* ─ Layout ─ */
".wrap{max-width:1040px;margin:0 auto;padding:16px 14px 40px}"
/* ─ Top Bar ─ */
".topbar{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px;"
"padding:14px 20px;border-radius:var(--r);"
"background:rgba(18,28,40,.8);backdrop-filter:blur(16px);margin-bottom:16px;"
"box-shadow:0 1px 0 rgba(80,240,195,.08)}"
".brand{font-size:18px;font-weight:900;letter-spacing:-.5px;font-family:'Manrope',sans-serif}"
".brand span{color:var(--ok)}"
".status-row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}"
".chip{display:inline-flex;align-items:center;gap:6px;padding:5px 10px;border-radius:999px;"
"border:1px solid var(--line);background:rgba(255,255,255,.03);font-size:12px;color:var(--muted)}"
".dot{width:7px;height:7px;border-radius:50%;background:var(--warn)}"
".dot.ok{background:var(--ok)}.dot.bad{background:var(--bad)}"
/* ─ Section Header ─ */
".sec-hdr{display:flex;align-items:center;justify-content:space-between;margin:18px 0 10px}"
".sec-hdr h2{font-size:15px;font-weight:700;color:var(--muted);text-transform:uppercase;letter-spacing:.06em}"
/* ─ Medication Grid ─ */
".med-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}"
"@media(max-width:680px){.med-grid{grid-template-columns:repeat(2,1fr)}}"
"@media(max-width:420px){.med-grid{grid-template-columns:1fr}}"
".med-card{background:var(--s-hi);border-radius:var(--r);"
"padding:20px 18px;position:relative;overflow:hidden;transition:background .2s;"
"box-shadow:0 4px 20px rgba(0,0,0,.25)}"
".med-card::before{content:'';position:absolute;top:0;left:0;right:0;height:3px;"
"background:linear-gradient(90deg,var(--ok),var(--blue));border-radius:var(--r) var(--r) 0 0;opacity:0;transition:opacity .2s}"
".med-card.has-med::before{opacity:1}"
".med-card.empty::before{background:var(--warn);opacity:.5}"
".med-label{font-size:11px;color:var(--muted);font-weight:600;text-transform:uppercase;letter-spacing:.05em}"
".med-num{font-size:11px;color:var(--muted);margin-bottom:4px}"
".med-name{font-size:14px;font-weight:700;margin:4px 0 10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;"
"color:var(--txt)}"
/* BIG pill count number */
".med-count{font-size:64px;font-weight:900;line-height:1;letter-spacing:-3px;font-family:'Manrope',sans-serif;"
"background:linear-gradient(135deg,var(--ok),var(--ok2));-webkit-background-clip:text;"
"-webkit-text-fill-color:transparent;background-clip:text}"
".med-count.zero{background:linear-gradient(135deg,#4a5568,#2d3748);-webkit-background-clip:text;background-clip:text}"
".med-unit{font-size:12px;color:var(--muted);margin-top:4px;margin-bottom:10px}"
".med-slots{font-size:11px;color:var(--muted);line-height:1.6}"
".med-ir{display:inline-flex;align-items:center;gap:4px;margin-top:8px;padding:3px 8px;"
"border-radius:999px;font-size:11px;font-weight:700}"
".med-ir.detected{background:rgba(34,211,168,.15);color:var(--ok);border:1px solid rgba(34,211,168,.3)}"
".med-ir.clear{background:rgba(255,255,255,.04);color:var(--muted);border:1px solid var(--line)}"
/* ─ System Strip ─ */
".sys-strip{display:flex;gap:8px;flex-wrap:wrap;padding:12px 16px;border-radius:var(--r);"
"background:var(--s-low)}"
".sys-item{display:flex;align-items:center;gap:6px;padding:4px 10px;border-radius:999px;"
"border:1px solid var(--line);font-size:12px}"
".sys-val{font-weight:700}"
/* ─ Card Generic ─ */
".card{background:var(--s-hi);border-radius:var(--r);overflow:hidden;box-shadow:0 8px 32px rgba(0,0,0,.3)}"
".card-hdr{padding:14px 18px;border-bottom:1px solid rgba(60,74,68,.5);display:flex;align-items:center;"
"justify-content:space-between;background:var(--s-top)}"
".card-hdr b{font-size:14px}"
".card-body{padding:14px 16px}"
/* ─ Sound Config ─ */
".snd-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}"
"@media(max-width:560px){.snd-grid{grid-template-columns:1fr}}"
".snd-row{display:flex;align-items:center;gap:8px;padding:8px 0;border-bottom:1px solid var(--line)}"
".snd-row:last-child{border-bottom:none}"
".snd-lbl{flex:1;font-size:13px;color:var(--muted)}"
".snd-num{width:64px;padding:6px 8px;border-radius:10px;border:none;"
"background:var(--s-top);color:var(--txt);font-size:14px;font-weight:700;"
"font-family:'Inter',ui-monospace,monospace;text-align:center}"
".snd-num:focus{outline:none;border-color:var(--ok);box-shadow:0 0 0 2px rgba(34,211,168,.2)}"
".snd-test{padding:5px 10px;border-radius:8px;border:1px solid rgba(34,211,168,.3);"
"background:rgba(34,211,168,.08);color:var(--ok);font-size:12px;font-weight:700;cursor:pointer}"
".snd-test:hover{background:rgba(34,211,168,.16)}"
/* ─ Servo Cards ─ */
".svc-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}"
"@media(max-width:560px){.svc-grid{grid-template-columns:repeat(2,1fr)}}"
".svc-card{background:var(--s-mid);border-radius:14px;padding:14px}"
".svc-title{font-size:12px;font-weight:700;margin-bottom:8px}"
".svc-row{display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin-top:6px}"
".svc-lbl{font-size:11px;color:var(--muted)}"
".svc-inp{width:52px;padding:5px 6px;border-radius:8px;border:1px solid var(--line);"
"background:rgba(255,255,255,.06);color:var(--txt);font-size:12px;font-family:ui-monospace,monospace}"
".svc-inp:focus{outline:none;border-color:var(--blue)}"
/* ─ Buttons ─ */
".btn{cursor:pointer;border-radius:12px;padding:8px 16px;font-size:13px;font-weight:700;"
"border:none;background:linear-gradient(135deg,var(--ok),var(--ok2));color:#002117;transition:opacity .15s}"
".btn:hover{opacity:.88}"
".btn.red{background:rgba(255,180,171,.15);color:var(--bad)}"
".btn.blue{background:var(--s-top);color:var(--muted)}"
".btn.sm{padding:5px 10px;font-size:12px;border-radius:8px}"
".btn-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}"
/* ─ Badge ─ */
".badge{padding:4px 10px;border-radius:999px;font-size:11px;font-weight:700;letter-spacing:.04em;"
"background:var(--s-top);color:var(--muted)}"
".badge.ok{background:rgba(80,240,195,.15);color:var(--ok)}"
".badge.bad{background:rgba(255,180,171,.12);color:var(--bad)}"
".badge.warn{background:rgba(255,207,143,.12);color:var(--warn)}"
".badge.mid{background:rgba(185,200,220,.1);color:var(--blue)}"
/* ─ Log ─ */
".log-box{background:var(--s-deep);border-radius:14px;"
"padding:12px;max-height:220px;overflow-y:auto;font-size:11px;line-height:1.5;"
"font-family:ui-monospace,monospace;color:#a5f3e8;white-space:pre-wrap;word-break:break-word}"
/* ─ WiFi Form ─ */
".field{display:flex;flex-direction:column;gap:6px;margin-bottom:12px}"
".field label{font-size:13px;font-weight:600;color:var(--muted)}"
".field input,.field select{padding:10px 12px;border-radius:12px;border:none;"
"background:var(--s-top);color:var(--txt);font-size:14px}"
".field input:focus,.field select:focus{outline:none;border-color:var(--ok)}"
/* ─ Camera ─ */
".cam-wrap{border-radius:var(--r);overflow:hidden;background:#000;aspect-ratio:4/3;width:100%}"
".cam-wrap img{width:100%;height:100%;display:block;object-fit:cover}"
/* ─ Tabs & Sensors ─ */
".tab-bar{display:flex;gap:10px;margin-bottom:20px;border-bottom:1px solid rgba(255,255,255,0.1);padding-bottom:10px;overflow-x:auto}"
".tab-btn{background:transparent;border:none;color:var(--muted);font-size:14px;font-weight:700;padding:8px 16px;cursor:pointer;border-radius:12px;transition:0.2s}"
".tab-btn:hover{background:rgba(255,255,255,0.05);color:var(--txt)}"
".tab-btn.active{background:var(--s-top);color:var(--ok)}"
".tab-pane{display:none}"
".tab-pane.active{display:block}"
".sns-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:16px}"
".sns-dist{font-size:36px;font-weight:800;letter-spacing:-.02em}"
".sns-unit{font-size:14px;color:var(--muted);margin-left:4px}"
".sns-bar-wrap{background:rgba(255,255,255,.06);border-radius:999px;height:12px;margin:14px 0 6px;overflow:hidden}"
".sns-bar{height:100%;border-radius:999px;transition:width .5s ease,background .5s ease}"
".sns-cfg-row{display:flex;gap:8px;margin-top:14px;flex-wrap:wrap}"
".sns-input{background:var(--s-top);border:1px solid var(--line);border-radius:10px;color:var(--txt);padding:6px 10px;font-size:13px;width:70px}"
".sns-label{font-size:11px;color:var(--muted);display:block;margin-bottom:2px}"
"</style></head><body>"

/* ── HEADER ── */
"<div class=wrap>"
"<div class=topbar>"
"<div class=brand>💊 Auto Pill <span>Dispenser</span></div>"
"<div class=status-row>"
"<div class=chip><span id=nd class=dot></span><span id=nt>Connecting…</span></div>"
"<div class='chip' style='font-family:ui-monospace,monospace'>IP: <span id=ip>--</span></div>"
"<div class=chip>🕐 <span id=rtcT>--:--:--</span></div>"
"<div class=chip id=netpieChip><span id=npDot class=dot></span>Cloud</div>"
"<button class=btn onclick=manual()>↻ Refresh</button>"
"</div></div>"

/* ── CAMERA ── */
"<div class=tab-bar>"
"<button id=tb-main class='tab-btn active' onclick=\"setTab('main')\">Dashboard</button>"
"<button id=tb-settings class='tab-btn' onclick=\"setTab('settings')\">Settings</button>"
"</div>"
"<div id=pane-main class='tab-pane active'>"
"<div id=camSection>"
"<div class=sec-hdr><h2>📷 Camera</h2>"
"<div style='display:flex;gap:8px;align-items:center'>"
"<a id=snapLink target=_blank class='btn blue btn-sm' style='text-decoration:none;font-size:12px'>📸 Snapshot</a>"
"<button class='btn blue btn-sm' onclick=camToggle()>⏸ Pause</button>"
"</div></div>"
"<div style='display:grid;grid-template-columns:2fr 1fr;gap:12px'>"
"<div class=cam-wrap><img id=camImg alt='Camera Stream'></div>"
"<div style='display:flex;flex-direction:column;gap:8px'>"
"<div class=card style='flex:1'><div class=card-hdr><b>Camera Controls</b><span id=camStateBadge class='badge mid'>Syncing</span></div><div class=card-body style='display:flex;flex-direction:column;gap:10px'>"
"<div style='display:flex;align-items:center;justify-content:space-between'><span style='font-size:12px;color:var(--muted)'>Quality</span><input id=camQuality type=number min=20 max=90 value=45 style='width:56px;padding:4px;border-radius:8px;border:none;background:var(--s-top);color:var(--txt);font-size:13px'><button class='btn blue btn-sm' onclick=camSaveBasic() style='font-size:11px'>Save</button></div>"
"<div style='display:flex;align-items:center;justify-content:space-between'><span style='font-size:12px;color:var(--muted)'>Brightness</span><input id=camBrightness type=range min=-2 max=2 step=1 value=0 style='flex:1;margin:0 10px' oninput='document.getElementById(\"camBrightnessVal\").textContent=this.value'><span id=camBrightnessVal class='badge mid'>0</span></div>"
"<div style='display:flex;align-items:center;justify-content:space-between'><span style='font-size:12px;color:var(--muted)'>Contrast</span><input id=camContrast type=range min=-2 max=2 step=1 value=0 style='flex:1;margin:0 10px' oninput='document.getElementById(\"camContrastVal\").textContent=this.value'><span id=camContrastVal class='badge mid'>0</span></div>"
"<div style='display:flex;align-items:center;justify-content:space-between'><span style='font-size:12px;color:var(--muted)'>Saturation</span><input id=camSaturation type=range min=-2 max=2 step=1 value=0 style='flex:1;margin:0 10px' oninput='document.getElementById(\"camSaturationVal\").textContent=this.value'><span id=camSaturationVal class='badge mid'>0</span></div>"
"<div style='display:flex;gap:6px;flex-wrap:wrap'><button class='btn blue btn-sm' onclick=camSaveTone() style='font-size:11px'>Save Tone</button><button class='btn blue btn-sm' onclick=camLoadState() style='font-size:11px'>Reload State</button></div>"
"<div style='display:flex;gap:6px;flex-wrap:wrap'>"
"<button class='btn btn-sm' onclick='camApplyProfile(\"smooth\")' style='font-size:11px'>Smooth</button>"
"<button class='btn btn-sm' onclick='camApplyProfile(\"balanced\")' style='font-size:11px'>Balanced</button>"
"<button class='btn btn-sm' onclick='camApplyProfile(\"sharp\")' style='font-size:11px'>Sharp</button>"
"</div>"
"<div style='display:flex;gap:6px'>"
"<button class='btn blue btn-sm' id=camMirrorBtn onclick=camToggleMirror() style='font-size:11px'>Mirror</button>"
"<button class='btn blue btn-sm' id=camFlipBtn onclick=camToggleFlip() style='font-size:11px'>Flip</button>"
"<button class='btn btn-sm' onclick=camRestoreDefault() style='font-size:11px'>Reset</button>"
"</div>"
"</div></div>"
"<div class=card><div class=card-hdr><b>Camera Status</b></div><div class=card-body style='font-size:12px;color:var(--muted);line-height:1.8'>"
"<div>Sensor: <span id=camSensorName class='sys-val'>--</span></div>"
"<div>Profile: <span id=camProfileText class='sys-val'>--</span></div>"
"<div>Mirror/Flip: <span id=camMirrorFlip class='sys-val'>--</span></div>"
"</div></div>"
"</div></div>"
"</div>"
"</div>"

/* ── MEDICATION STATUS ── */
"<div class=sec-hdr><h2>🧿 IR Detection Status</h2><span id=medUpdT class='badge mid'>Live</span></div>"
"<div class='med-grid' id=medGrid></div>"
"<div id=distSection>"
"<div class=sec-hdr><h2>Distance Sensor Status</h2><span id=snsUpdT class='badge mid'>Live</span></div>"
"<div class='sns-grid' id=snsGrid></div>"
"</div>"

/* ── SYSTEM STATUS ── */
"<div class=sec-hdr><h2>⚙️ System</h2></div>"
"<div class=sys-strip>"
"<div class=sys-item><span class=dot id=rtcDot></span>RTC <span class='sys-val' id=rtcB>--</span></div>"
"<div class=sys-item><span class=dot id=pcfDot></span>IR (PCF8574) <span class='sys-val badge' id=pcfB>--</span></div>"
"<div class=sys-item><span class=dot id=pcaDot></span>Servo (PCA9685) <span class='sys-val badge' id=pcaB>--</span></div>"
"<div class=sys-item><span class=dot id=ctpDot></span>Touch <span class='sys-val badge' id=ctpB>--</span></div>"
"<div class=sys-item><span class=dot id=npDot2></span>NETPIE <span class='sys-val badge' id=npB>--</span></div>"
"<div class=sys-item>Offline: <span class='sys-val badge' id=npPend>--</span></div>"
"</div>"

"</div>"
"<div id=pane-settings class='tab-pane'>"
/* ── SOUND CONFIG (tech only) ── */
"<div id=sndSection>"
"<div class=sec-hdr><h2>🔊 Sound Track Config</h2><span class='badge warn'>Tech Only</span></div>"
"<div class=card>"
"<div class=card-hdr><b>Track Numbers</b>"
"<span id=sndSaveState class='badge mid'></span></div>"
"<div class=card-body>"
"<div class=snd-grid>"
"<div>"
/* Left column */
"<div class=snd-row>"
"<span class=snd-lbl>🚨 Alarm (main)</span>"
"<input class=snd-num id=sndAlarm type=number min=1 max=199>"
"<button class=snd-test onclick=sndTest(document.getElementById('sndAlarm').value)>▶</button>"
"</div>"
"<div class=snd-row>"
"<span class=snd-lbl>💉 Dispensed (TH)</span>"
"<input class=snd-num id=sndDispTh type=number min=1 max=199>"
"<button class=snd-test onclick=sndTest(document.getElementById('sndDispTh').value)>▶</button>"
"</div>"
"<div class=snd-row>"
"<span class=snd-lbl>↩️ Returned (TH)</span>"
"<input class=snd-num id=sndRetTh type=number min=1 max=199>"
"<button class=snd-test onclick=sndTest(document.getElementById('sndRetTh').value)>▶</button>"
"</div>"
"<div class=snd-row>"
"<span class=snd-lbl>❌ No Meds (TH)</span>"
"<input class=snd-num id=sndNomTh type=number min=1 max=199>"
"<button class=snd-test onclick=sndTest(document.getElementById('sndNomTh').value)>▶</button>"
"</div>"
"</div>"
"<div>"
/* Right column */
"<div class=snd-row>"
"<span class=snd-lbl>💉 Dispensed (EN)</span>"
"<input class=snd-num id=sndDispEn type=number min=1 max=199>"
"<button class=snd-test onclick=sndTest(document.getElementById('sndDispEn').value)>▶</button>"
"</div>"
"<div class=snd-row>"
"<span class=snd-lbl>↩️ Returned (EN)</span>"
"<input class=snd-num id=sndRetEn type=number min=1 max=199>"
"<button class=snd-test onclick=sndTest(document.getElementById('sndRetEn').value)>▶</button>"
"</div>"
"<div class=snd-row>"
"<span class=snd-lbl>❌ No Meds (EN)</span>"
"<input class=snd-num id=sndNomEn type=number min=1 max=199>"
"<button class=snd-test onclick=sndTest(document.getElementById('sndNomEn').value)>▶</button>"
"</div>"
"<div class=snd-row>"
"<span class=snd-lbl>🔘 Button Sound</span>"
"<input class=snd-num id=sndButton type=number min=1 max=199>"
"<button class=snd-test onclick=sndTest(document.getElementById('sndButton').value)>▶</button>"
"</div>"
"</div>"
"</div>"
"<div class=btn-row>"
"<button class=btn onclick=sndSave()>💾 Save Track Numbers</button>"
"<button class='btn blue' onclick=sndLoad()>↺ Reload</button>"
"</div>"
"</div></div></div>"

/* ── SERVO CONTROL ── */
"<div id=svSection>"
"<div class=sec-hdr><h2>🤖 Servo Channels</h2>"
"<small style='color:var(--muted);font-size:11px;font-family:ui-monospace,monospace'>PCA9685 @0x40</small></div>"
"<div class=card>"
"<div class='card-body'>"
"<div class='svc-grid' id=svGrid></div>"
"<p style='color:var(--muted);font-size:12px;margin-top:10px'>Home/Work angle 0–180° (Default: Home=66°, Work=33°)</p>"
"</div></div></div>"

/* ── LOGS ── */
"<div id=logSection>"
"<div class=sec-hdr><h2>📋 Live Logs</h2><span id=logState class='badge mid'>Live</span></div>"
"<div class=log-box id=liveLog>Loading…</div>"
"</div>"

/* ── WIFI CONFIG ── */
"<div>"
"<div class=sec-hdr><h2>📶 WiFi Config</h2></div>"
"<div class=card>"
"<div class=card-body>"
"<div class=field>"
"<label>Current: <span id=wifiCurrentSsid style='color:var(--ok)'>--</span>"
" (<span id=ip2>--</span>)</label></div>"
"<form method=POST action=/wifi/save style='display:flex;flex-direction:column;gap:0'>"
"<div class=field><label>Networks <button type=button class='btn sm blue' onclick=scanWifi()>Scan</button></label>"
"<select id=wifiList class='field input' style='padding:8px 10px' onchange='document.getElementById(\"ssidIn\").value=this.value'>"
"<option value=''>-- Select or type below --</option></select></div>"
"<div class=field><label>SSID</label><input id=ssidIn name=ssid required placeholder='MyHomeNetwork'></div>"
"<div class=field><label>Password</label><input name=pass type=password placeholder='(blank if open)'></div>"
"<div class=btn-row>"
"<button type=submit class=btn>Save &amp; Connect</button>"
"<button type=button class='btn red' onclick='if(confirm(\"Delete WiFi?\"))fetch(\"/wifi/forget\",{method:\"POST\"}).then(()=>location.reload())'>Delete WiFi</button>"
"</div></form>"
"</div></div></div>"

/* ── ACCESS CODES ── */
"<div>"
"<div class=sec-hdr><h2>🔑 Access Codes</h2></div>"
"<div class=card><div class=card-body>"
"<form id=accessForm style='display:flex;flex-direction:column;gap:0' onsubmit='return saveAccessCodes(event)'>"
"<div class=field><label>Customer Code</label><input id=cloudCodeIn name=cloud_code placeholder='Customer code'></div>"
"<div class=field><label>Technician Code</label><input id=techCodeIn name=tech_code placeholder='Tech code'></div>"
"<div class=field><label>Admin Code</label><input id=adminCodeIn name=admin_code placeholder='Admin code'></div>"
"<div class=btn-row>"
"<button type=submit class=btn>Save Codes</button>"
"<span id=accessSaveState class='badge mid'></span>"
"</div></form>"
"</div></div></div>"

"</div>" /* end pane-settings */
"</div>" /* wrap */

/* ── JAVASCRIPT ── */
"<script>"
"const READ_ONLY=(location.pathname==='/monitor');"
"const EP='/status.json',SS='/servo/state',LG='/logs/tail',SC='/sound/config',SK='/sound/save',AS='/access/state',AU='/access/save',CS='/camera/state';"

/* Slot labels */
"const SLOTS=['Morning Pre','Morning Post','Lunch Pre','Lunch Post','Dinner Pre','Dinner Post','Bedtime'];"

/* Escape HTML */
"function esc(v){return String(v===undefined||v===null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}"
"function fetchJson(u,o){return fetch(u,o).then(r=>{if(!r.ok){return r.text().then(t=>{var e=new Error('http');e.status=r.status;e.body=t||'';throw e;});}return r.json();});}"
"function fetchText(u,o){return fetch(u,o).then(r=>{if(!r.ok){return r.text().then(t=>{var e=new Error('http');e.status=r.status;e.body=t||'';throw e;});}return r.text();});}"
"function sessionExpired(e){return !!(e&&e.status===401);}"
"function setTopError(msg){document.getElementById('nt').textContent=msg||'ERROR';dot('nd',false);}"
"function setTab(t){['main','settings'].forEach(x=>{"
"document.getElementById('tb-'+x).className='tab-btn'+(t===x?' active':'');"
"document.getElementById('pane-'+x).className='tab-pane'+(t===x?' active':'');"
"});}"

/* Slot summary */
"function slotSum(mask,times){mask=parseInt(mask||0)||0;var p=[];"
"for(var i=0;i<7;i++){if(mask&(1<<i)){var t=(times&&times[i])?times[i]:'--:--';p.push(SLOTS[i]+' @ '+t);}}"
"return p.length?p.join('<br>'):'<span style=\"color:var(--muted)\">No schedule set</span>';}"

/* Build med grid */
"function buildMedGrid(){var g=document.getElementById('medGrid');if(!g||g.children.length===6)return;"
"for(var i=0;i<6;i++){"
"var d=document.createElement('div');d.className='med-card';d.id='mc'+i;"
"d.innerHTML='<div class=med-label>IR Module <span class=med-num>'+(i+1)+'</span></div>'"
"+'<div class=med-name id=mn'+i+'>—</div>'"
"+'<div class=med-count id=mc'+i+'c>—</div>'"
"+'<div class=med-unit id=mu'+i+'>Sensor state</div>'"
"+'<div class=med-slots id=ms'+i+'></div>'"
"+'<div id=mir'+i+' class=med-ir>IR: —</div>';"
"g.appendChild(d);}}"

/* Update med card */
"function updateMed(m,idx,times,irVal){"
"var card=document.getElementById('mc'+idx);if(!card)return;"
"var name=m&&m.name?esc(m.name):'Unnamed';"
"var detected=(irVal===0);"
"document.getElementById('mn'+idx).textContent=name;"
"var ce=document.getElementById('mc'+idx+'c');"
"ce.textContent=detected?'DETECTED':'CLEAR';"
"ce.className='med-count'+(detected?'':' zero');"
"document.getElementById('mu'+idx).textContent=detected?'Pill detected':'Path clear';"
"document.getElementById('ms'+idx).innerHTML='Input: '+(detected?'0 (pill present)':'1 (clear)')+'<br>'+slotSum(m?m.slots:0,times);"
"card.className='med-card '+(detected?'has-med':'empty');"
"var ir=document.getElementById('mir'+idx);"
"ir.className='med-ir '+(detected?'detected':'clear');"
"ir.textContent='IR: '+(detected?'DETECTED':'CLEAR');}"

"function snsPct(s){if(!s||!s.valid||s.pill_count<0||!s.max_pills)return 0;return Math.max(0,Math.min(100,Math.round((s.pill_count/s.max_pills)*100)));}"
"function snsColor(p){if(p>60)return'#4dd7b0';if(p>25)return'#6db8ff';if(p>0)return'#f59e0b';return'#ef4444';}"
"function snsState(s,p){if(!s||!s.present)return'NO SENSOR';if(!s.valid)return'NO READING';if(s.is_empty)return'EMPTY';if(s.is_full)return'FULL';return p<25?'LOW':'READY';}"
"function snsClass(s,p){if(!s||!s.present||s.is_empty)return'bad';if(!s.valid||p<25)return'warn';return'ok';}"
"function buildSnsGrid(){var g=document.getElementById('snsGrid');if(!g||g.children.length===6)return;"
"for(var i=0;i<6;i++){"
"var d=document.createElement('div');d.className='card';d.id='sns_c'+i;"
"d.innerHTML='<div class=card-hdr><b>Module '+(i+1)+'</b><span id=sns_bg'+i+' class=\"badge mid\">--</span></div>'"
"+'<div class=card-body>'"
"+'<div class=sns-dist><span id=sns_dt'+i+'>--</span><span class=sns-unit>mm</span></div>'"
"+'<div class=sns-bar-wrap><div id=sns_br'+i+' class=sns-bar style=\"width:0%\"></div></div>'"
"+'<div style=\"font-size:14px;font-weight:700;margin-bottom:8px\"><span id=sns_ct'+i+'>--</span></div>'"
"+'<div style=\"font-size:12px;color:var(--muted);line-height:1.7\">Raw: <span id=sns_rw'+i+'>--</span> mm<br>Filtered: <span id=sns_fl'+i+'>--</span> mm<br>Address: <span id=sns_ad'+i+'>0x29</span></div>'"
"+'<div class=sns-cfg-row id=sns_cfg'+i+'>'"
"+'<div><label class=sns-label>Full</label><input id=sns_fd'+i+' type=number class=sns-input></div>'"
"+'<div><label class=sns-label>Per pill</label><input id=sns_ph'+i+' type=number class=sns-input></div>'"
"+'<div><label class=sns-label>Max</label><input id=sns_mp'+i+' type=number class=sns-input></div>'"
"+'<div style=\"display:flex;align-items:flex-end\"><button class=\"btn blue sm\" onclick=\"snsSave('+i+')\">Save</button></div>'"
"+'</div></div>';"
"g.appendChild(d);"
"if(READ_ONLY){var cfg=document.getElementById('sns_cfg'+i);if(cfg)cfg.style.display='none';}"
"}}"
"function snsSave(ch){var fd=new URLSearchParams();fd.set('ch',ch);fd.set('full_dist_mm',document.getElementById('sns_fd'+ch).value);fd.set('pill_height_mm',document.getElementById('sns_ph'+ch).value);fd.set('max_pills',document.getElementById('sns_mp'+ch).value);fetch('/sensors/config',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:fd}).then(r=>r.json()).then(()=>snsPoll()).catch(()=>{});}"

/* Build servo grid */
"function buildSV(){"
"var g=document.getElementById('svGrid');if(!g||g.children.length>=6)return;"
"for(var i=0;i<6;i++){"
"var d=document.createElement('div');d.className='svc-card';"
"if(READ_ONLY){"
"d.innerHTML='<div class=svc-title>Servo CH'+i+'</div>'"
"+'<div class=svc-row><span class=svc-lbl>Home</span><span class=\"sys-val\" id=svHro'+i+'>66</span>°'"
"+'<span class=svc-lbl style=\"margin-left:8px\">Work</span><span class=\"sys-val\" id=svWro'+i+'>33</span>°</div>'"
"+'<div style=\"font-size:11px;color:var(--muted);margin-top:4px\">Pos: <span id=svC'+i+'>—</span>°</div>';"
"}else{"
"d.innerHTML='<div class=svc-title>Servo CH'+i+' <span class=\"badge\" id=svB'+i+'>—</span></div>'"
"+'<div class=svc-row>'"
"+'<span class=svc-lbl>Home°</span><input class=svc-inp id=svH'+i+' type=number min=0 max=180 value=66>'"
"+'<span class=svc-lbl>Work°</span><input class=svc-inp id=svW'+i+' type=number min=0 max=180 value=33>'"
"+'<button class=\"btn sm\" onclick=\"svSave('+i+')\">💾</button></div>'"
"+'<div class=svc-row>'"
"+'<button class=\"btn sm blue\" onclick=\"svGo('+i+',\\'home\\')\">◀ Home</button>'"
"+'<button class=\"btn sm\" onclick=\"svGo('+i+',\\'work\\')\">Work ▶</button>'"
"+'<button class=\"btn sm warn\" onclick=\"svTest('+i+')\">⚡ Test</button></div>'"
"+'<div style=\"font-size:11px;color:var(--muted);margin-top:4px\">Pos: <span id=svC'+i+'>—</span>°</div>';"
"}"
"g.appendChild(d);}}"

/* Servo fetch */
"function svGo(ch,p){fetch('/servo/'+p+'?ch='+ch).then(()=>svPoll());}"
"function svTest(ch){fetch('/servo/test?ch='+ch);setTimeout(svPoll,1400);}"
"function svSave(ch){var h=document.getElementById('svH'+ch).value,w=document.getElementById('svW'+ch).value;"
"fetch('/servo/set?ch='+ch+'&home='+h+'&work='+w).then(()=>svPoll());}"
"function svPoll(){fetchJson(SS).then(j=>{j.channels.forEach(c=>{"
"if(READ_ONLY){var hr=document.getElementById('svHro'+c.ch),wr=document.getElementById('svWro'+c.ch);"
"if(hr)hr.textContent=c.home;if(wr)wr.textContent=c.work;}"
"else{"
"var h=document.getElementById('svH'+c.ch),w=document.getElementById('svW'+c.ch);"
"if(h&&!h.dataset.loaded){h.value=c.home;h.dataset.loaded='1';}"
"if(w&&!w.dataset.loaded){w.value=c.work;w.dataset.loaded='1';}"
"}"
"var ce=document.getElementById('svC'+c.ch);if(ce)ce.textContent=c.cur>=0?c.cur:'—';});"
"}).catch(e=>{if(sessionExpired(e))setTopError('SESSION EXPIRED');});}"

/* Sound config */
"function sndLoad(){fetchJson(SC).then(j=>{"
"document.getElementById('sndAlarm').value=j.alarm||1;"
"document.getElementById('sndDispTh').value=j.disp_th||83;"
"document.getElementById('sndRetTh').value=j.ret_th||84;"
"document.getElementById('sndNomTh').value=j.nomeds_th||85;"
"document.getElementById('sndDispEn').value=j.disp_en||86;"
"document.getElementById('sndRetEn').value=j.ret_en||87;"
"document.getElementById('sndNomEn').value=j.nomeds_en||88;"
"document.getElementById('sndButton').value=j.button||10;"
"document.getElementById('sndSaveState').textContent='Loaded ✓';"
"}).catch(e=>document.getElementById('sndSaveState').textContent=sessionExpired(e)?'Session expired':'Load failed');}"

"function sndSave(){"
"var fd=new URLSearchParams();"
"['alarm','disp_th','ret_th','nomeds_th','disp_en','ret_en','nomeds_en','button'].forEach(function(k){"
"var map={alarm:'sndAlarm',disp_th:'sndDispTh',ret_th:'sndRetTh',nomeds_th:'sndNomTh',"
"disp_en:'sndDispEn',ret_en:'sndRetEn',nomeds_en:'sndNomEn',button:'sndButton'};"
"fd.set(k,document.getElementById(map[k]).value);});"
"fetch(SK,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:fd})"
".then(r=>r.json()).then(j=>{document.getElementById('sndSaveState').textContent=j.ok?'Saved ✓':'Error';})"
".catch(()=>document.getElementById('sndSaveState').textContent='Failed');}"

"function sndTest(n){n=parseInt(n);if(!n||n<1||n>199)return;"
"fetch('/sound/play?track='+n).then(r=>r.json()).then(j=>{if(!j.ok)alert('Play failed');}).catch(()=>alert('Error'));}"


/* WiFi scan */
"function scanWifi(){"
"var sl=document.getElementById('wifiList');sl.innerHTML='<option>Scanning…</option>';"
"fetch('/wifi/scan').then(r=>r.json()).then(j=>{"
"sl.innerHTML='<option value=\"\">-- Select Network --</option>';"
"j.forEach(n=>{var o=document.createElement('option');o.value=n.ssid;"
"o.textContent=n.ssid+' ('+n.rssi+' dBm)';sl.appendChild(o);});"
"}).catch(()=>sl.innerHTML='<option value=\"\">Scan Failed</option>');}"

/* Access codes */
"function loadAccessCodes(){fetch(AS).then(r=>r.json()).then(j=>{"
"document.getElementById('cloudCodeIn').value=j.cloud_code||'';"
"document.getElementById('techCodeIn').value=j.tech_code||'';"
"document.getElementById('adminCodeIn').value=j.admin_code||'';"
"document.getElementById('accessSaveState').textContent='Loaded';"
"}).catch(()=>document.getElementById('accessSaveState').textContent='Load failed');}"
"function saveAccessCodes(ev){if(ev)ev.preventDefault();"
"var fd=new URLSearchParams();"
"fd.set('cloud_code',document.getElementById('cloudCodeIn').value);"
"fd.set('tech_code',document.getElementById('techCodeIn').value);"
"fd.set('admin_code',document.getElementById('adminCodeIn').value);"
"fetch(AU,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:fd})"
".then(r=>r.json()).then(j=>document.getElementById('accessSaveState').textContent=j&&j.ok?'Saved':'Failed')"
".catch(()=>document.getElementById('accessSaveState').textContent='Failed');return false;}"

/* Badge helper */
"function badge(id,cls,txt){var el=document.getElementById(id);if(!el)return;el.className='badge'+(cls?' '+cls:'');el.textContent=txt;}"
"function dot(id,ok){var el=document.getElementById(id);if(!el)return;el.className='dot '+(ok?'ok':'bad');}"

/* Log poll */
"function logPoll(){if(READ_ONLY)return;"
"fetch(LG).then(r=>r.text()).then(t=>{"
"var el=document.getElementById('liveLog');if(!el)return;"
"var stick=(el.scrollTop+el.clientHeight+24)>=el.scrollHeight;"
"el.textContent=t&&t.length?t:'No logs yet.';"
"if(stick)el.scrollTop=el.scrollHeight;"
"badge('logState','mid','Live');"
"}).catch(()=>badge('logState','bad','Offline'));}"

"function snsPoll(){fetchJson('/sensors.json').then(j=>{"
"var g=document.getElementById('snsGrid');if(!g)return;"
"buildSnsGrid();"
"var chs=Array.isArray(j.channels)?j.channels:[];"
"chs.forEach(function(s){"
"var i=(s.ch!==undefined)?s.ch:((s.idx||1)-1);"
"var p=snsPct(s);"
"var state=snsState(s,p);"
"var cls=snsClass(s,p);"
"badge('sns_bg'+i,cls,state);"
"var dist=(s.valid&&s.filtered_mm>=0)?s.filtered_mm:'--';"
"var raw=(s.raw_mm!==undefined&&s.raw_mm>=0)?s.raw_mm:'--';"
"document.getElementById('sns_dt'+i).textContent=dist;"
"document.getElementById('sns_rw'+i).textContent=raw;"
"document.getElementById('sns_fl'+i).textContent=dist;"
"document.getElementById('sns_ad'+i).textContent='0x'+Number(s.addr||41).toString(16).toUpperCase();"
"document.getElementById('sns_ct'+i).textContent=(s.pill_count>=0?s.pill_count:'-')+'/'+(s.max_pills||'-')+' pills';"
"var bar=document.getElementById('sns_br'+i);if(bar){bar.style.width=p+'%';bar.style.background=snsColor(p);}"
"var fd=document.getElementById('sns_fd'+i);if(fd&&document.activeElement!==fd)fd.value=s.full_dist_mm||0;"
"var ph=document.getElementById('sns_ph'+i);if(ph&&document.activeElement!==ph)ph.value=s.pill_height_mm||0;"
"var mp=document.getElementById('sns_mp'+i);if(mp&&document.activeElement!==mp)mp.value=s.max_pills||0;"
"});"
"document.getElementById('snsUpdT').textContent=new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit',second:'2-digit'});"
"}).catch(e=>{if(sessionExpired(e))setTopError('SESSION EXPIRED');else badge('snsUpdT','bad','Offline');});}"

/* Main render */
"function render(j){"
"document.getElementById('ip').textContent=j.ip||'0.0.0.0';"
"document.getElementById('ip2').textContent=j.ip||'0.0.0.0';"
"document.getElementById('rtcT').textContent=j.rtc_time||'--:--:--';"
"document.getElementById('nt').textContent=j.wifi_connected?('Online'+(j.ssid?' • '+j.ssid:'')):'AP Mode';"
"document.getElementById('wifiCurrentSsid').textContent=(j.ssid&&j.ssid.length)?j.ssid:'Not connected';"
"dot('nd',j.wifi_connected);"
"dot('npDot',j.netpie_connected);"
"dot('npDot2',j.netpie_connected);"
"dot('rtcDot',j.rtc_present);"
"dot('pcfDot',j.pcf_present);"
"dot('pcaDot',j.pca_present);"
"dot('ctpDot',j.ctp_present);"
"badge('rtcB',j.rtc_present?'ok':'bad',j.rtc_present?'OK':'NO');"
"badge('pcfB',j.pcf_present?'ok':'bad',j.pcf_present?'FOUND':'MISSING');"
"badge('pcaB',j.pca_present?'ok':'bad',j.pca_present?'FOUND':'MISSING');"
"badge('ctpB',j.ctp_present?'ok':'bad',j.ctp_present?'OK':'NO');"
"badge('npB',j.netpie_connected?'ok':'bad',j.netpie_connected?'ONLINE':'OFFLINE');"
"badge('npPend','warn',j.offline_pending?'YES':'NO');"
"document.getElementById('medUpdT').textContent=new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit',second:'2-digit'});"
"var meds=Array.isArray(j.meds)?j.meds:[];var times=Array.isArray(j.slot_times)?j.slot_times:[];"
"meds.forEach(function(m,idx){"
"var irKey='ir_p'+idx;var irVal=(j[irKey]!==undefined)?j[irKey]:1;"
"updateMed(m,idx,times,irVal);});"
"}"

/* Tick */
"function tick(){fetch(EP).then(r=>r.json()).then(j=>render(j)).catch(e=>{"
"document.getElementById('nt').textContent='ERROR';dot('nd',false);});}"

/* Manual refresh */
"function manual(){tick();svPoll();logPoll();snsPoll();"
"if(!READ_ONLY){var ci=document.getElementById('camImg');if(ci)ci.src='http://'+location.hostname+':81/stream?'+Date.now();}}"

/* Camera functions */
"var camPaused=false;"
"function camToggle(){camPaused=!camPaused;var ci=document.getElementById('camImg');"
"if(camPaused){ci.removeAttribute('src');document.querySelector('[onclick=camToggle()]').textContent='▶ Resume';}"
"else{ci.src='http://'+location.hostname+':81/stream?'+Date.now();document.querySelector('[onclick=camToggle()]').textContent='⏸ Pause';}}"
"function camSet(p){fetch('/camera/set?'+p).then(r=>r.json()).catch(()=>{});}"
"function camSaveBasic(){camSet('quality='+document.getElementById('camQuality').value);}"
"function camSaveTone(){camSet('brightness='+document.getElementById('camBrightness').value+'&contrast='+document.getElementById('camContrast').value+'&saturation='+document.getElementById('camSaturation').value);}"
"function camLoadState(){document.getElementById('camStateBadge').textContent='Syncing...';fetch('/camera/state').then(r=>r.json()).then(j=>{"
"if(j.quality!==undefined)document.getElementById('camQuality').value=j.quality;"
"if(j.brightness!==undefined){document.getElementById('camBrightness').value=j.brightness;document.getElementById('camBrightnessVal').textContent=j.brightness;}"
"if(j.contrast!==undefined){document.getElementById('camContrast').value=j.contrast;document.getElementById('camContrastVal').textContent=j.contrast;}"
"if(j.saturation!==undefined){document.getElementById('camSaturation').value=j.saturation;document.getElementById('camSaturationVal').textContent=j.saturation;}"
"if(j.sensor_name)document.getElementById('camSensorName').textContent=j.sensor_name;"
"if(j.profile)document.getElementById('camProfileText').textContent=j.profile;"
"if(j.mirror!==undefined){var bm=document.getElementById('camMirrorBtn');bm.dataset.on=j.mirror?'1':'0';bm.style.opacity=j.mirror?0.6:1;}"
"if(j.vflip!==undefined){var bf=document.getElementById('camFlipBtn');bf.dataset.on=j.vflip?'1':'0';bf.style.opacity=j.vflip?0.6:1;}"
"document.getElementById('camMirrorFlip').textContent='M:'+(j.mirror?'ON':'OFF')+' / F:'+(j.vflip?'ON':'OFF');"
"document.getElementById('camStateBadge').textContent='Synced';}).catch(()=>{document.getElementById('camStateBadge').textContent='Error';});}"
"function camApplyProfile(n){"
"if(n==='smooth'){camSet('quality=35&delay=0');document.getElementById('camQuality').value=35;}"
"else if(n==='balanced'){camSet('quality=45&delay=0');document.getElementById('camQuality').value=45;}"
"else{camSet('quality=65&delay=0');document.getElementById('camQuality').value=65;}}"
"function camToggleMirror(){var btn=document.getElementById('camMirrorBtn');"
"var on=btn.dataset.on==='1';btn.dataset.on=on?'0':'1';"
"camSet('mirror='+(on?0:1));btn.style.opacity=on?0.6:1;}"
"function camToggleFlip(){var btn=document.getElementById('camFlipBtn');"
"var on=btn.dataset.on==='1';btn.dataset.on=on?'0':'1';"
"camSet('vflip='+(on?0:1));btn.style.opacity=on?0.6:1;}"
"function camRestoreDefault(){document.getElementById('camQuality').value=45;"
"camSet('quality=45&delay=0&mirror=0&vflip=0');}"

/* Read-only mode decoration */
"if(READ_ONLY){"
"document.getElementById('sndSection').style.display='none';"
"document.getElementById('svSection').style.display='none';"
"document.getElementById('logSection').style.display='none';"
"document.getElementById('camSection').style.display='none';"
"document.getElementById('tb-settings').style.display='none';"
"}"

/* Init */
"buildMedGrid();buildSnsGrid();buildSV();"
"document.getElementById('snapLink').href='http://'+location.hostname+':81/capture';"
"if(!READ_ONLY){"
"var ci=document.getElementById('camImg');"
"if(ci)ci.src='http://'+location.hostname+':81/stream';"
"}"
"tick();svPoll();logPoll();snsPoll();"
"if(!READ_ONLY){sndLoad();loadAccessCodes();camLoadState();setInterval(snsPoll,2500);}"
"setInterval(tick,3000);setInterval(svPoll,4000);setInterval(logPoll,2500);"
"</script></body></html>";
