#pragma once

// ─────────────────────────────────────────────────────────────────────────────
//  index_html.h — Unified Dashboard HTML (MyHome Status)
//  แก้ UI / สี / layout ที่นี่ได้โดยไม่ต้องแตะ web_server.c
// ─────────────────────────────────────────────────────────────────────────────

static const char index_html[] =
/* ── HEAD + CSS ── */
"<!doctype html><html lang=th><head>"
"<meta charset=utf-8>"
"<meta name=viewport content='width=device-width,initial-scale=1'>"
"<title>Automatic Pill Dispenser</title>"
"<style>"
/* ─ CSS Variables ─ */
":root{--bg0:#031018;--bg1:#061822;--line:rgba(255,255,255,.08);"
"--text:#e9fbff;--muted:rgba(233,251,255,.70);"
"--ok:#22c55e;--bad:#fb7185;--warn:#fbbf24;"
"--r16:16px;--r20:20px;--shadow:0 18px 60px rgba(0,0,0,.35)}"
"*{box-sizing:border-box}"
/* ─ Body + Background ─ */
"body{margin:0;color:var(--text);"
"font-family:ui-sans-serif,system-ui,'Segoe UI',Roboto,Arial;"
"background:radial-gradient(900px 420px at 20% -10%,rgba(45,212,191,.22),transparent 60%),"
"radial-gradient(900px 420px at 85% 0%,rgba(56,189,248,.18),transparent 55%),"
"linear-gradient(180deg,var(--bg0),var(--bg1));min-height:100vh}"
".wrap{max-width:980px;margin:0 auto;padding:18px}"
/* ─ Header ─ */
"header{border:1px solid var(--line);"
"background:linear-gradient(180deg,rgba(255,255,255,.05),rgba(255,255,255,.02));"
"border-radius:var(--r20);padding:14px;box-shadow:var(--shadow);"
"display:flex;gap:12px;align-items:center;justify-content:space-between;"
"backdrop-filter:blur(10px)}"
".brand{display:flex;gap:12px;align-items:center}"
".logo{width:42px;height:42px;border-radius:14px;"
"background:linear-gradient(135deg,rgba(45,212,191,.95),rgba(56,189,248,.85));"
"border:1px solid rgba(255,255,255,.14);box-shadow:0 14px 40px rgba(45,212,191,.20)}"
".title b{font-size:16px}"
".title small{display:block;color:var(--muted);margin-top:3px;font-size:12px}"
".meta{display:flex;gap:10px;flex-wrap:wrap;justify-content:flex-end;align-items:center}"
/* ─ Pills + Dots ─ */
".pill{display:inline-flex;align-items:center;gap:8px;padding:8px 10px;"
"border-radius:999px;border:1px solid var(--line);"
"background:rgba(255,255,255,.03);color:var(--muted);font-size:12px;white-space:nowrap}"
".dot{width:8px;height:8px;border-radius:50%}"
".dot.ok{background:var(--ok)}.dot.bad{background:var(--bad)}.dot.warn{background:var(--warn)}"
".mono{font-family:ui-monospace,Menlo,Consolas,monospace}"
/* ─ Tab Bar ─ */
".tabbar{display:flex;gap:8px;margin-top:12px}"
".tab{flex:1;padding:12px 0;border-radius:14px;border:1px solid var(--line);"
"background:rgba(255,255,255,.03);color:var(--muted);"
"font-weight:700;font-size:13px;cursor:pointer;text-align:center;"
"transition:all .18s ease}"
".tab.active{background:linear-gradient(135deg,rgba(45,212,191,.20),rgba(56,189,248,.12));"
"border-color:rgba(45,212,191,.40);color:var(--text);"
"box-shadow:0 0 18px rgba(45,212,191,.12)}"
".tab:hover:not(.active){background:rgba(255,255,255,.06)}"
".panel{display:none}.panel.active{display:block}"
/* ─ Camera ─ */
".cam-full{background:#000;border-radius:16px;overflow:hidden;width:100%;aspect-ratio:4/3}"
".cam-full img{width:100%;height:100%;display:block;object-fit:cover}"
/* ─ Sections ─ */
".section{margin-top:12px;border:1px solid var(--line);"
"background:rgba(255,255,255,.03);border-radius:var(--r20);"
"box-shadow:var(--shadow);overflow:hidden}"
".sh{padding:12px 14px;border-bottom:1px solid var(--line);"
"display:flex;justify-content:space-between;align-items:center;gap:10px}"
".sh b{font-size:13px}.sh small{color:var(--muted)}"
".sb{padding:14px}"
/* ─ Grids ─ */
".grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}"
".mgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}"
".sgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}"
"@media(max-width:720px){.grid2,.sgrid{grid-template-columns:1fr}}"
"@media(max-width:520px){.mgrid{grid-template-columns:repeat(2,1fr)}}"
/* ─ Mini Card ─ */
".mini{border:1px solid var(--line);background:rgba(255,255,255,.03);"
"border-radius:var(--r16);padding:10px;display:flex;flex-direction:column;gap:6px}"
".mt{display:flex;justify-content:space-between;align-items:center}"
".mt b{font-size:13px}"
/* ─ Badges ─ */
".badge{padding:5px 10px;border-radius:999px;font-weight:900;font-size:12px;"
"border:1px solid var(--line);background:rgba(255,255,255,.04);color:var(--muted)}"
".badge.ok{border-color:rgba(34,197,94,.35);background:rgba(34,197,94,.12);color:#bff7d1}"
".badge.bad{border-color:rgba(251,113,133,.35);background:rgba(251,113,133,.12);color:#ffd3dc}"
".badge.mid{border-color:rgba(45,212,191,.30);background:rgba(45,212,191,.10);color:#d5fffb}"
".badge.warn{border-color:rgba(251,191,36,.35);background:rgba(251,191,36,.12);color:#fff2c6}"
".muted{color:var(--muted);font-size:12px}"
/* ─ Buttons ─ */
".btn{cursor:pointer;border:1px solid rgba(45,212,191,.30);"
"background:rgba(45,212,191,.10);color:var(--text);"
"border-radius:12px;padding:8px 10px;font-weight:900;font-size:12px}"
".btn:hover{filter:brightness(1.08)}"
/* ─ Servo Card ─ */
".svc{border:1px solid var(--line);background:rgba(255,255,255,.03);"
"border-radius:var(--r16);padding:12px;display:flex;flex-direction:column;gap:8px}"
".svc-top{display:flex;justify-content:space-between;align-items:center}"
".svc-top b{font-size:13px}"
".svc-row{display:flex;gap:6px;align-items:center;flex-wrap:wrap}"
".svc-lbl{color:var(--muted);font-size:11px;white-space:nowrap}"
".svc-num{width:58px;padding:5px 7px;border-radius:8px;"
"border:1px solid var(--line);background:rgba(255,255,255,.06);"
"color:var(--text);font-size:12px;font-family:ui-monospace,monospace}"
".svc-num:focus{outline:1px solid rgba(45,212,191,.5);border-color:#2dd4bf}"
/* ─ Small Buttons (servo actions) ─ */
".sb2{cursor:pointer;border-radius:10px;padding:5px 10px;"
"font-weight:800;font-size:12px;border:1px solid var(--line);"
"background:rgba(255,255,255,.06);color:var(--text)}"
".sb2:hover{filter:brightness(1.15)}.sb2:active{filter:brightness(.85)}"
".sb2.hm{border-color:rgba(56,189,248,.35);background:rgba(56,189,248,.12);color:#bae6fd}"
".sb2.wk{border-color:rgba(34,197,94,.35);background:rgba(34,197,94,.12);color:#bbf7d0}"
".sb2.ts{border-color:rgba(251,191,36,.35);background:rgba(251,191,36,.10);color:#fef08a}"
".svc-cur{color:var(--muted);font-size:11px;font-family:ui-monospace,monospace}"
"</style></head><body>"

/* ── BODY ── */
"<div class=wrap>"
"<header>"
"<div class=brand><div class=logo></div>"
"<div class=title><b>Automatic Pill Dispenser &bull; Dashboard</b>"
"<small>Cam + IR(PCF8574) + Servo(PCA9685) + RTC &bull; ESP32-P4</small>"
"</div></div>"
"<div class=meta>"
"<div class=pill><span id=nd class='dot warn'></span><span id=nt>Connecting&hellip;</span></div>"
"<div class='pill mono'>IP: <span id=ip>0.0.0.0</span></div>"
"<div class=pill>Updated: <span id=lu>&mdash;</span></div>"
"<button class=btn onclick=manual()>Refresh</button>"
"</div></header>"

/* ── Tab Bar ── */
"<div class=tabbar>"
"<button class='tab active' id=tab0 onclick=showTab(0)>&#128247; Camera</button>"
"<button class=tab id=tab1 onclick=showTab(1)>&#128268; Modules</button>"
"<button class=tab id=tab2 onclick=showTab(2)>&#128246; WiFi</button>"
"</div>"

/* ── Panel 0: Camera ── */
"<div class='panel active' id=panel0>"
"<div class=section>"
"<div class=sh><b>Camera Feed (MJPEG)</b>"
"<small class=mono><span id=camSensor>OV5647</span> 800x640 &bull; <a id=snapLink target='_blank' style='color:#2dd4bf'>Snapshot</a></small>"
"</div>"
"<div class=sb style='padding:12px'>"
"<div class=cam-full><img id=camImg alt='Camera Stream'></div>"
"</div></div>"
"<div class=section>"
"<div class=sh><b>Camera Controls</b><small class=mono>/camera/set</small></div>"
"<div class=sb><div class=grid2>"
"<div class=svc><div class=svc-top><b>Image Quality</b><span class='badge mid' id=camQBadge>60</span></div>"
"<div class=svc-row><span class=svc-lbl>JPEG</span><input class=svc-num id=camQuality type=number min=20 max=90 value=60>"
"<button class=sb2 onclick='camSaveQuality()'>&#128190; Save</button></div>"
"<div class=muted>Higher = sharper still image, but uses more bandwidth</div></div>"
"<div class=svc><div class=svc-top><b>Stream Smoothness</b><span class='badge mid' id=camDelayBadge>0 ms</span></div>"
"<div class=svc-row><span class=svc-lbl>Delay</span><input class=svc-num id=camDelay type=number min=0 max=300 value=0>"
"<button class=sb2 onclick='camSaveDelay()'>&#128190; Save</button></div>"
"<div class=muted>Lower delay = smoother stream, higher delay = lighter load</div></div>"
"<div class=svc><div class=svc-top><b>Orientation</b><span class='badge mid' id=camOrientBadge>Normal</span></div>"
"<div class=svc-row><button class='sb2 hm' id=camMirrorBtn onclick='camToggleMirror()'>Mirror OFF</button>"
"<button class='sb2 wk' id=camFlipBtn onclick='camToggleFlip()'>Flip OFF</button>"
"<button class='sb2 ts' onclick='camRestoreDefault()'>Restore</button></div>"
"<div class=muted>Useful when the camera is mounted upside-down or mirrored</div></div>"
"<div class=svc><div class=svc-top><b>Camera Status</b></div>"
"<div class='muted mono'>Sensor: <span id=camSensorState>--</span></div>"
"<div class='muted mono'>Profile: quality=<span id=camQState>--</span>, delay=<span id=camDelayState>--</span>ms</div>"
"<div class='muted mono'>Mirror=<span id=camMirrorState>--</span>, Flip=<span id=camFlipState>--</span></div></div>"
"</div></div></div></div>"

/* ── Panel 1: Modules ── */
"<div class=panel id=panel1>"

/* IR Sensors */
"<div class=section>"
"<div class=sh><b>IR Sensors (P0&ndash;P5)</b>"
"<small class=mono>PCF8574 @0x20 &bull; <span id=pcfS>&mdash;</span></small>"
"</div>"
"<div class=sb><div class=mgrid id=irGrid></div>"
"<div class=muted style='margin-top:10px'>0=DETECTED, 1=CLEAR &bull; Raw: <span class=mono id=irRaw>&mdash;</span></div>"
"</div></div>"

/* Servo Channels */
"<div class=section>"
"<div class=sh><b>Servo Channels (CH0&ndash;CH5)</b>"
"<small class=mono>PCA9685 @0x40 &bull; <span id=pcaS>&mdash;</span></small>"
"</div>"
"<div class=sb><div class=sgrid id=svGrid></div>"
"<div class=muted style='margin-top:10px'>Home/Work = angle 0&ndash;180&deg; (Default: Home=66&deg;, Work=33&deg;)</div>"
"</div></div>"

/* System Cards */
"<div class=section>"
"<div class=sh><b>System</b><small class=mono>/status.json</small></div>"
"<div class=sb><div class=grid2>"
/* RTC card */
"<div class=mini><div class=mt><b>RTC</b><span id=rtcB class=badge>&mdash;</span></div>"
"<div class='muted mono'>DS3231 @0x68 &bull; <span id=rtcS>&mdash;</span></div>"
"<div class='muted mono'>Time: <span id=rtcT>&mdash;</span></div></div>"
/* Devices card */
"<div class=mini><div class=mt><b>Devices</b></div>"
"<div class='muted mono'>PCF8574: <span id=pcfB class=badge>&mdash;</span></div>"
"<div class='muted mono'>PCA9685: <span id=pcaB class=badge>&mdash;</span></div>"
"</div>"
/* Touch card */
"<div class=mini style='grid-column:1/-1'><div class=mt><b>Touch Screen (FT6336U @0x38)</b><span id=ctpB class=badge>&mdash;</span></div>"
"<div class='muted mono' style='margin-top:6px'>Status: <span id=ctpS>&mdash;</span> &bull; X: <span id=tX>&mdash;</span> &bull; Y: <span id=tY>&mdash;</span></div>"
"</div>"
"</div></div></div>"
"<div class=section>"
"<div class=sh><b>Cloud & Medication Shadow</b><small class=mono>NETPIE + local cache</small></div>"
"<div class=sb><div class=grid2>"
"<div class=mini><div class=mt><b>Cloud Sync</b><span id=npB class=badge>&mdash;</span></div>"
"<div class='muted mono'>Broker: <span id=npConn>&mdash;</span></div>"
"<div class='muted mono'>Shadow: <span id=shLoaded>&mdash;</span> &bull; Schedule: <span id=shEn>&mdash;</span></div>"
"<div class='muted mono'>Last RX: <span id=npRx>&mdash;</span> &bull; Pending: <span id=npPend>&mdash;</span></div></div>"
"<div class=mini><div class=mt><b>Medication Snapshot</b><span id=medSnapB class='badge mid'>6 Modules</span></div>"
"<div class='muted'>Shows medicine names, remaining pills, and active dose windows from shadow cache</div></div>"
"</div><div class=mgrid id=medShadowGrid style='margin-top:12px'></div></div></div>"
"</div>"  /* panel1 */

/* ── Panel 2: WiFi Setup ── */
"<div class=panel id=panel2>"
"<div class=section>"
"<div class=sh><b>WiFi Configuration</b><small class=mono>Network Connect</small></div>"
"<div class=sb>"
"<form method='POST' action='/wifi/save' style='display:flex;flex-direction:column;gap:12px'>"
"<div style='display:flex;flex-direction:column;gap:4px'>"
"<label class=muted>Detected Networks <button type=button class=sb2 onclick='scanWifi()' style='padding:2px 8px;margin-left:6px'>&#8635;</button></label>"
"<select id=wifiList class='svc-num' style='width:100%;font-size:16px;padding:10px' onchange='document.getElementById(\"ssidIn\").value=this.value'>"
"<option value=''>-- Select or type below --</option>"
"</select>"
"</div>"
"<div style='display:flex;flex-direction:column;gap:4px'>"
"<label class=muted>Home WiFi Name (SSID)</label>"
"<input id=ssidIn name='ssid' class='svc-num' style='width:100%;font-size:16px;padding:10px;text-align:left' required placeholder='MyHomeNetwork'>"
"</div>"
"<div style='display:flex;flex-direction:column;gap:4px'>"
"<label class=muted>Password</label>"
"<input name='pass' type='password' class='svc-num' style='width:100%;font-size:16px;padding:10px;text-align:left' placeholder='(Leave blank if open)'>"
"</div>"
"<button type='submit' class='btn' style='padding:12px;font-size:14px;margin-top:8px;background:rgba(34,197,94,0.2)'>Save &amp; Connect</button>"
"<button type='button' class='btn' style='padding:12px;font-size:14px;background:rgba(251,113,133,0.2);color:#fb7185' onclick='if(confirm(\"Disconnect and Forget WiFi?\")) fetch(\"/wifi/forget\",{method:\"POST\"}).then(()=>location.reload())'>Delete WiFi (Forget)</button>"
"</form>"
"</div></div>"
"</div>"

"</div>" /* wrap */

/* ── JavaScript ── */
"<script>"
/* Tab switching */
"var _ct=0;"
"const READ_ONLY=(location.pathname==='/monitor');"
"function showTab(n){"
"[0,1,2].forEach(function(i){"
"document.getElementById('tab'+i).classList.toggle('active',i===n);"
"document.getElementById('panel'+i).classList.toggle('active',i===n);});"
"_ct=n;"
"var img=document.getElementById('camImg');"
"if(n===0&&!READ_ONLY){if(!img.getAttribute('src'))"
"img.src='http://'+location.hostname+':81/stream';}"
"else img.removeAttribute('src');"
"if(n===2 && document.getElementById('wifiList').children.length<=1) scanWifi();"
"}"
"function scanWifi(){"
"var sl=document.getElementById('wifiList');sl.innerHTML='<option>Scanning...</option>';"
"fetch('/wifi/scan').then(r=>r.json()).then(j=>{"
"sl.innerHTML='<option value=\"\">-- Select Network --</option>';"
"j.forEach(n=>{"
"var o=document.createElement('option');o.value=n.ssid;o.textContent=n.ssid+' ('+n.rssi+'dBm)';"
"sl.appendChild(o);"
"});"
"}).catch(()=>sl.innerHTML='<option value=\"\">Scan Failed</option>');"
"}"
/* API endpoints */
"const EP='/status.json',SS='/servo/state',CS='/camera/state',CU='/camera/set';"
"const ig=document.getElementById('irGrid'),sg=document.getElementById('svGrid');"
/* IR grid builder */
"function mkIR(i){var d=document.createElement('div');d.className='mini';"
"d.innerHTML='<div class=mt><b>IR P'+i+'</b><span class=badge id=irB'+i+'>&mdash;</span></div>"
"<div class=muted>Val: <span class=mono id=irV'+i+'>&mdash;</span></div>';return d;}"
"for(var i=0;i<6;i++) ig.appendChild(mkIR(i));"
/* Servo grid builder */
"function mkSV(i){var d=document.createElement('div');d.className='svc';"
"if(READ_ONLY){d.innerHTML='<div class=svc-top><b>Servo CH'+i+'</b><span class=badge id=svB'+i+'>&mdash;</span></div>"
"<div class=svc-row><span class=svc-lbl>Home&deg;</span><span class=mono id=svHro'+i+'>66</span>"
"<span class=svc-lbl>Work&deg;</span><span class=mono id=svWro'+i+'>33</span></div>"
"<div class=svc-cur>Pos: <span id=svC'+i+'>&mdash;</span>&deg;</div>"
"<div class=muted>Read-only monitor mode</div>';return d;}"
"d.innerHTML='<div class=svc-top><b>Servo CH'+i+'</b><span class=badge id=svB'+i+'>&mdash;</span></div>"
"<div class=svc-row><span class=svc-lbl>Home&deg;</span>"
"<input class=svc-num id=svH'+i+' type=number min=0 max=180 value=66>"
"<span class=svc-lbl>Work&deg;</span>"
"<input class=svc-num id=svW'+i+' type=number min=0 max=180 value=33>"
"<button class=sb2 onclick=\"svSave('+i+')\">&#128190;</button></div>"
"<div class=svc-row>"
"<button class=\"sb2 hm\" onclick=\"svGo('+i+',\\x27home\\x27)\">&#9664; Home</button>"
"<button class=\"sb2 wk\" onclick=\"svGo('+i+',\\x27work\\x27)\">Work &#9654;</button>"
"<button class=\"sb2 ts\" onclick=\"svTest('+i+')\">&#9889; Test</button></div>"
"<div class=svc-cur>Pos: <span id=svC'+i+'>&mdash;</span>&deg;</div>';return d;}"
"for(var i=0;i<6;i++) sg.appendChild(mkSV(i));"
/* Servo fetch helpers */
"function svGo(ch,pos){fetch('/servo/'+pos+'?ch='+ch,{cache:'no-store'}).then(function(){svPoll();});}"
"function svTest(ch){fetch('/servo/test?ch='+ch,{cache:'no-store'});setTimeout(svPoll,1400);}"
"function svSave(ch){var h=document.getElementById('svH'+ch).value,w=document.getElementById('svW'+ch).value;"
"fetch('/servo/set?ch='+ch+'&home='+h+'&work='+w,{cache:'no-store'}).then(function(){svPoll();});}"
"function svPoll(){fetch(SS,{cache:'no-store'}).then(function(r){return r.json();}).then(function(j){"
"j.channels.forEach(function(c){"
"if(READ_ONLY){var hr=document.getElementById('svHro'+c.ch),wr=document.getElementById('svWro'+c.ch);if(hr)hr.textContent=c.home;if(wr)wr.textContent=c.work;}"
"var h=document.getElementById('svH'+c.ch),w=document.getElementById('svW'+c.ch);"
"if(h&&document.activeElement!==h) h.value=c.home;"
"if(w&&document.activeElement!==w) w.value=c.work;"
"var el=document.getElementById('svC'+c.ch);if(el)el.textContent=c.cur>=0?c.cur:'--';});"
"}).catch(function(){});}"
"function camSetBadgeText(id,text){var el=document.getElementById(id);if(el)el.textContent=text;}"
"function camApplyState(j){"
"document.getElementById('camSensor').textContent=j.sensor||'OV5647';"
"document.getElementById('camSensorState').textContent=j.sensor||'OV5647';"
"document.getElementById('camQuality').value=j.jpeg_quality;"
"document.getElementById('camDelay').value=j.stream_delay_ms;"
"document.getElementById('camQState').textContent=j.jpeg_quality;"
"document.getElementById('camDelayState').textContent=j.stream_delay_ms;"
"document.getElementById('camMirrorState').textContent=j.mirror?'ON':'OFF';"
"document.getElementById('camFlipState').textContent=j.vflip?'ON':'OFF';"
"camSetBadgeText('camQBadge',j.jpeg_quality);"
"camSetBadgeText('camDelayBadge',j.stream_delay_ms+' ms');"
"document.getElementById('camMirrorBtn').textContent='Mirror '+(j.mirror?'ON':'OFF');"
"document.getElementById('camFlipBtn').textContent='Flip '+(j.vflip?'ON':'OFF');"
"document.getElementById('camOrientBadge').textContent=(j.mirror||j.vflip)?('M'+j.mirror+' / F'+j.vflip):'Normal';"
"}"
"function camPoll(){if(READ_ONLY)return;fetch(CS,{cache:'no-store'}).then(function(r){return r.json();}).then(function(j){camApplyState(j);}).catch(function(){});}"
"function camSet(params){fetch(CU+'?'+params,{cache:'no-store'}).then(function(r){return r.json();}).then(function(j){camApplyState(j);manual();}).catch(function(){});}"
"function camSaveQuality(){camSet('quality='+document.getElementById('camQuality').value);}"
"function camSaveDelay(){camSet('delay='+document.getElementById('camDelay').value);}"
"function camToggleMirror(){camSet('mirror='+(document.getElementById('camMirrorState').textContent==='ON'?0:1));}"
"function camToggleFlip(){camSet('vflip='+(document.getElementById('camFlipState').textContent==='ON'?0:1));}"
"function camRestoreDefault(){camSet('quality=60&delay=0&mirror=0&vflip=0');}"
/* Status polling */
"function dotNet(ok){document.getElementById('nd').className='dot '+(ok?'ok':'bad');}"
"function badge(id,cls,txt){var el=document.getElementById(id);if(!el)return;"
"el.className='badge'+(cls?' '+cls:'');el.textContent=txt;}"
"function slotSummary(mask,times){mask=parseInt(mask||0,10)||0;var parts=[];"
"for(var i=0;i<7;i++){if(mask&(1<<i)){var tm=(times&&times[i])?times[i]:'--:--';parts.push(SLOT_LABELS[i]+' @ '+tm);}}"
"return parts.length?parts.join(' • '):'ยังไม่กำหนดรอบจ่าย';}"
"function renderShadowMeds(j){var host=document.getElementById('medShadowGrid');if(!host)return;"
"var meds=Array.isArray(j.meds)?j.meds:[];var times=Array.isArray(j.slot_times)?j.slot_times:[];var html='';"
"meds.forEach(function(m){var name=(m&&m.name)?escapeHtml(m.name):'ยังไม่ตั้งชื่อยา';var count=(m&&m.count!==undefined)?m.count:0;"
"var badgeCls=count>0?'mid':'warn';"
"html+='<div class=mini><div class=mt><b>Module '+((m&&m.id)||'?')+'</b><span class=\"badge '+badgeCls+'\">'+count+' pills</span></div>';"
"html+='<div class=\"muted mono\">'+name+'</div>';"
"html+='<div class=muted>'+escapeHtml(slotSummary(m?m.slots:0,times))+'</div></div>';});"
"host.innerHTML=html||'<div class=mini><div class=muted>No medication shadow data</div></div>';"
"badge('medSnapB','mid',(meds.length||0)+' Modules');}"
"function renderCloudState(j){"
"badge('npB',j.netpie_connected?'ok':'bad',j.netpie_connected?'BROKER OK':'BROKER OFF');"
"document.getElementById('npConn').textContent=j.netpie_connected?'CONNECTED':'DISCONNECTED';"
"document.getElementById('shLoaded').textContent=j.shadow_loaded?'LOADED':'NOT READY';"
"document.getElementById('shEn').textContent=j.shadow_enabled?'ENABLED':'DISABLED';"
"document.getElementById('npRx').textContent=(typeof j.netpie_last_rx_sec==='number'&&j.netpie_last_rx_sec>=0)?(j.netpie_last_rx_sec+'s ago'):'--';"
"document.getElementById('npPend').textContent=j.offline_pending?'YES':'NO';}"
"function now(){return new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit',second:'2-digit'});}"
"function render(j){"
"document.getElementById('lu').textContent=now();"
"document.getElementById('ip').textContent=j.ip||'0.0.0.0';"
"document.getElementById('nt').textContent=j.wifi_connected?'Online':'AP Setup Mode';"
"dotNet(true);"
"document.getElementById('pcfS').textContent=j.pcf_present?'FOUND':'NOT FOUND';"
"document.getElementById('irRaw').textContent=(j.ir_byte||'--').toUpperCase();"
"for(var i=0;i<6;i++){var val=j['ir_p'+i],ok=(val!==undefined);"
"var bc=j.pcf_present?(ok?(val===0?'ok':'mid'):'warn'):'bad';"
"var bt=j.pcf_present?(ok?(val===0?'DETECTED':'CLEAR'):'READ FAIL'):'NO PCF';"
"badge('irB'+i,bc,bt);"
"var vel=document.getElementById('irV'+i);if(vel)vel.textContent=ok?val:'--';}"
"document.getElementById('pcaS').textContent=j.pca_present?'FOUND':'NOT FOUND';"
"for(var i=0;i<6;i++) badge('svB'+i,j.pca_present?'ok':'bad',j.pca_present?'READY':'NO PCA');"
"badge('rtcB',j.rtc_present?'ok':'bad',j.rtc_present?'OK':'NO');"
"document.getElementById('rtcS').textContent=j.rtc_present?'FOUND':'NOT FOUND';"
"document.getElementById('rtcT').textContent=j.rtc_time||'--';"
"badge('pcfB',j.pcf_present?'ok':'bad',j.pcf_present?'FOUND':'NOT FOUND');"
"badge('pcaB',j.pca_present?'ok':'bad',j.pca_present?'FOUND':'NOT FOUND');"
"badge('ctpB',j.ctp_present?'ok':'bad',j.ctp_present?'FOUND':'NOT FOUND');"
"document.getElementById('ctpS').textContent=j.ctp_present?(j.touch_active?'TOUCH DETECTED':'IDLE'):'NO DEVICE';"
"document.getElementById('tX').textContent=j.touch_active?j.touch_x:'--';"
"document.getElementById('tY').textContent=j.touch_active?j.touch_y:'--';"
"renderCloudState(j);"
"renderShadowMeds(j);}"
"function tick(){fetch(EP,{cache:'no-store'}).then(function(r){return r.json();})"
".then(function(j){render(j);}).catch(function(e){"
"document.getElementById('nt').textContent='ERROR';dotNet(false);});}"
"function manual(){tick();svPoll();"
"if(!READ_ONLY)document.getElementById('camImg').src='http://'+location.hostname+':81/stream?'+Date.now();}"
"document.getElementById('snapLink').href='http://'+location.hostname+':81/capture';"
"if(READ_ONLY){document.getElementById('tab0').style.display='none';showTab(1);}else{showTab(0);document.getElementById('camImg').src='http://'+location.hostname+':81/stream';camPoll();}"
"tick();svPoll();"
"setInterval(tick,3000);setInterval(svPoll,3000);if(!READ_ONLY)setInterval(camPoll,4000);"
"</script></body></html>";
